### PR TITLE
Added Polish translation of Single access type version

### PR DESCRIPTION
**Pull request by kfinc**
I have added the Polish translation of the Ultimate consent form (Single access type version).

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you! @djarecka would you be kind to review/approve the translation?

**Comment by yarikoptic** [comment]
d'oh, and I totally missed that there was also #30  which was proposed already almost a year ago proposed by @mkoculak!  That is sad that I have missed/didn't act upon it causing duplication of effort. Please accept my apologies!
Dear @djarecka , please review and state which one has better wording, ideally we should meld them into a single version and acknowledge all participants.

**Comment by djarecka** [comment]
@yarikoptic - I've been just reviewing this one. Have some suggestions (still haven't finished) but overall looks great!

One question to you, especially seeing the older version that has very different style, is if this should be more like direct translation or free translation? 

@kfinc translation is not very direct, sometimes merges information from 2 different paragraphs (to avoid repetition that are in the English version). I believe the full text contains all important information and reads very well!

I've just read quickly @mkoculak translation and it's also great! However, it was definitely written thinking about more literal translation, and some of the sentences looks not as natural to me (it is just my opinion).

@yarikoptic  - I can try to merge the versions (and send to authors to review, they are better in writing than me anyway :), but the question to you is if this should be more literal translation and keeps the structure of the paragraphs etc., or this can be free translation trat sounds better for Polish readers. Have you had this discussion with other translation?

**Comment by mkoculak** [comment]
@yarikoptic - hey, no worries.
I was actually planning to write to you about it around the anniversary ;)

As for my version, as @djarecka said, I was going for literal vibe, so it would feel more legal-like. I checked it with my friends (a translator and a lawyer) and tested the text on some 200+ participants (but probably they wouldn't admit that often that they did not fully understand it).
Nevertheless, looking forward to getting a Polish version merged soon!

**Comment by yarikoptic** [comment]
I would go for literal. As you have mentioned even English version could be more human friendly. But it is not to be digestible by other legal species. And I think those communicate similar language ;-)

**Comment by kfinc** [comment]
Thanks @djarecka and @yarikoptic!

@djarecka, that's true, we intentionally merged two paragraphs due to repetition in the English version:

2nd paragraph: 

> The data we share with the general public will not have your name on it, only a code number, so people will not know your name or which data are yours. In addition, we will not share any other information that we think might help people who know you guess which data are yours. 

Part of the 5th paragraph: 

> The data will not have your name on it, only a code number, so people will not know your name or which data are yours. In addition, the data will not include data that we think might help people who know you guess which data are yours, such as your facial features or the date that you participated."

I've prepared this translation with my friend Monika Boruta-Żywiczyńska (English translator). We tried to make it as easy to read and understand for our participants, but I understand if you prefer a more literal version. 

Looking forward to the Polish version!

**Comment by djarecka** [comment]
@mkoculak - I didn't mean to say that something is unintelligible in your version, I'm sure that participants did understand if they read it. 

Since @kfinc spent also time to think about the translation and came up with some really nice wording, it might be best if she reviews #30 and suggests some changes. I really think that both versions are great  and it's unlikely that I will bring to the conversation something better. It is not necessary, but it would be great if at the end both institutes are happy with the version accepted here.

**Comment by djarecka** [comment]
@kfinc - looks like we were writing at the same time, didn't see your answer before posting mine :)

**Comment by kfinc** [comment]
@djarecka, thanks! I'll add my suggestions to #30.

**Comment by mkoculak** [comment]
@djarecka Sorry! I was not implying that at all, just wanted to give some background in case it would prove itself useful.
And yes, please substitute stuff from #30 with some nice wording as much as needed. :)

**Comment by yarikoptic** [comment]
Dear @djarecka ... it seems that only you could move us forward here by adopting alternative wording from #30 into this PR for constructing "ultimate" translation!  If you would like, I could then find an additional Polish speaking reviewer for yet another "independent" round of review if it would be desired

**Comment by djarecka** [comment]
@yarikoptic - will work on this later this week on next one

**Comment by mkoculak** [comment]
@yarikoptic - right, it got stuck in a limbo for no reason. sorry!

I was not sure how to elegantly insert changes into this pull request, so I updated the text in my initial proposition.

I saved most of the text from @kfinc and her colleague, adding/changing things only when I felt the translation diverted from the original too much or wording was not precise enough.

@djarecka - hope this will make it easier for you :)

**Comment by djarecka** [comment]
Thanks @mkoculak ! So I will  read the one that is in #30

**Comment by yarikoptic** [comment]
"superseded" by #30, which is now merged. Thanks everyone!

**Pull request closed without merging**
