### PR TITLE
Added initial version of the logo

### PR DESCRIPTION
**Pull request by AsykaKolbacyka**
Uncle @yarikoptic demanded me to prepare a logo for the project. This is an initial version which I might improve upon.
It is based on BIDS logo (Yarik said that license should allow for derivative work).

### CODE REVIEW

**Comment by bpoldrack** [comment]
Nice! I like the idea!

**Comment by yarikoptic** [comment]
@AsykaKolbacyka do not get scared whenever you next `git push` would not work -- I had pushed various changes which start to make use of the logo.  You could see how it would look in the final form if you visit url from "Details" in above "All checks have passed" which would lead to https://open-brain-consent--69.org.readthedocs.build/en/69/

**Comment by yarikoptic** [comment]
If other @con/obc people would like it in general, we would need to make 2nd version with white instead of black for brain/paper.  black would be used in favicon and PDF, and white one in the html version.

**Comment by yarikoptic** [comment]
well, without feedback I will just merge and then we could change if so decided.

**Pull request merged**
