### PR TITLE
one can single out subjects from biomedical data

### LINKED ISSUE #107: one cannot single out subjects
I'm not sure about this:
> it has become clear that one cannot single out subjects from biomedical data and/or MRI scans (including fMRI profiles from connectivity)

Shouldn't this be "it has become clear that one **can** single out subjects from biomedical data and/or MRI scans"?

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #107.

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
fix sounds correct to me!  @con/gdpr -- agree?

**Comment by yarikoptic** [comment]
hey @all-contributors please add @DimitriPapadopoulos for bug

**Comment by yarikoptic** [comment]
ok, I will assume no objections, will proceed

**Comment by CPernet** [comment]
?? how can we ensure all translations are correct -- @con/i18n to review

**Comment by DimitriPapadopoulos** [comment]
@CPernet That was in the _credit_ page, I assumed this specific page has not been translated.

**Comment by yarikoptic** [comment]
> @CPernet That was in the _credit_ page, I assumed this specific page has not been translated.

FWIW that is what I also assumed since it lacked the version indicator in the header like the pages which being translated have.

**Pull request merged**
