### PR TITLE
Gdpr updates with language split

### PR DESCRIPTION
**Pull request by CPernet**
language split and index updates
@con/vanessasaurus duplicate? 

Closes: #43
Closes: #29 (chrome auto translates ultimate)

### CODE REVIEW

**Comment by yarikoptic** [comment]
I am comparing now to the one from @vborghe (https://github.com/con/open-brain-consent/issues/43#issuecomment-623182756) and would like to bring both histories together so both contributions are in the history/acknowleded.
@CPernet   What is the `.zh-Hans`? why not just `.zh`?

**Comment by yarikoptic** [comment]
Thanks again @CPernet @vborghe ! I have pushed my merge of @vborghe 's work, which in that merge commit cf69bd65ee37b29fbd9e657af7d7b8deb3158598 describes how I resolved conflicts (what took from that branch).  Then I pushed more of various changes.  Please review final form -- you could get to it by expanding "Show all checks" and clicking on "Details" for RTD (ATM the url is https://open-brain-consent--46.org.readthedocs.build/en/46/ which probably would stay like that even if more pushed to this branch/PR).  When looks all good, we would be able to merge and then I could embed versions to each one of those following #42 (didn't want to pollute this already large PR)

**Comment by yarikoptic** [comment]
Sorry, I am impatient, let's just merge and then fixup what needs to be fixed up if anything ;)

**Comment by CPernet** [comment]
zh-Hans is Chinese simplified (as indicated in the translation) --> that's the ISO you recommended following

**Comment by yarikoptic** [comment]
He he. So it is defined on that page https://www.w3schools.com/tags/ref_language_codes.asp which I originally pointed out. I went to https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes where I didn't find it, thus started to ask. I think we should be safe with just two letters abbreviation in this case.

**Pull request merged**
