### PR TITLE
anonymization → de-identification

### LINKED ISSUE #106: "Anonymization"
Please do not use the word _Anonymization_. It has a specific and complex definition in the EU under the GDPR. See for example:
* [Opinion 05/2014 on Anonymisation Techniques](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf)
* [AEPD-EDPS joint paper on 10 misunderstandings related to anonymisation](https://edps.europa.eu/data-protection/our-work/publications/papers/aepd-edps-joint-paper-10-misunderstandings-related_en)

I have found using the term "anonymization" is one of the main sources of misunderstanding between US ans EU researchers.

Instead, use pseudonymization or de-identification depending on the context.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #106.

### CODE REVIEW

**Comment by CPernet** [comment]
@yarikoptic this merging should not happen -- de-identification is the term used by the US Health Insurance Portability and Accountability Act (HIPPA) and as such you can retain patients ID which akin to pseudonymization (to make it clear US-deidentified data as defined in HIPPA remains personal under GDPR) 

by contrast anomymization as a clear-cut data status

**Comment by DimitriPapadopoulos** [comment]
@CPernet 
> by contrast anomymization as a clear-cut data status

The meaning of "_anomymization_" differs widely between the US and the EU. I'm not sure what you mea&n by "clear-cut data status".

**Comment by CPernet** [comment]
then psedonymized is the proper term, de-identified is HIPAA specific

**Comment by DimitriPapadopoulos** [comment]
To make things clear:
* "_Anonymization_" has a specific and very restrictive meaning meaning under GDPR:
  * [Opinion 05/2014 on Anonymisation Techniques](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf)
  * [AEPD-EDPS joint paper on 10 misunderstandings related to anonymisation](https://edps.europa.eu/data-protection/our-work/publications/papers/aepd-edps-joint-paper-10-misunderstandings-related_en)
* On the other hand, "_de-identification_" under HIPAA and "_pseudonymization_" under GDPR are similar.
* The idea here is to "_pseudonymize_" or "_de-identify_" data, as it is often unfeasible to "_anonymize_" neuroimaging data in the GDPR sense.
* Hence I recommend you use the term "_de-identification_", as in "_pseudonymization_", because the term "_anonymization_" (as in the GDPR) is misused here.

**Comment by CPernet** [comment]
I agree with all the above :-) except 'Hence I recommend you use the term "de-identification", as in "pseudonymization", because the term "anonymization" (as in the GDPR) is misused here.' why? to be american centric?

**Comment by DimitriPapadopoulos** [comment]
I find "_pseudonymization_" too specific. The idea is to use a term that covers attempts to de-identify data, ranging from simple peudonymization to anonymization. The only term that comes to mind is "_de-identification_". I acknowledge the term has been hijacked by HIPAA to mean something specific, but that's certainbly less specific than "_anonymization_" under GDPR. I cannot find an alternative term to de-identification in its broad (not HIPAA) sense.

**Comment by CPernet** [comment]
ok but then we must define first de-identification to make sure people understand what you mean (I would actually copy/paste the points you made above since they are correct)

**Comment by DimitriPapadopoulos** [comment]
I totally agree. We need a glossary with some basic terms:
* de-identification (in the broad sense)
* de-identification (as in HIPAA)
* pseudonymization: may involve more than changing names to pseudonyms but I do not think the term is precisely defined
* anonymization (as in the GDPR)
* anonymization in the broad sense?

**Comment by CPernet** [comment]
what about

- anonymization: a process that involves removing sufficient
elements so that a natural person can no longer be identified (ISO 29100:2011)
- de-identification:  concept from the US Health Insurance Portability and Accountability Act (HIPPA) which does not involve irreversibility as anonymization does
- pseudonymization: is defined by GDPR as a process that removes information about identity which may or may not change the status of data from personal to anonymous (it does not for brain imaging data, because the EU court of justice indicated that  the possibility of identification is enough to consider data as personal)
 
Unless specifically mentioned, we used here de-identification in the generic sense, meaning removing obvious features leading to identification (names, addresses, maybe facial information from MRI).

**Comment by DimitriPapadopoulos** [comment]
Yes, looks good.

Is [ISO 29100:2011](https://www.iso.org/standard/45123.html) equivalent to the [G29 opinion on anonymization techniques](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf)? I haven't read [ISO 29100:2011](https://www.iso.org/standard/45123.html) as I cannot find the PDF on the [web site of the ISO/IEC Information Technology Task Force](https://jtc1info.org/).

By the way, do you have a link to this decision: _the EU court of justice indicated that the possibility of identification is enough to consider data as personal_?

**Comment by CPernet** [comment]
sure - case from IP address - https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2933781

**Comment by DimitriPapadopoulos** [comment]
On the other hand, Wikipedia defines "_[pseudonymization](https://en.wikipedia.org/wiki/Pseudonymization)_" as a "_[de-identification](https://en.wikipedia.org/wiki/De-identification)_" procedure, hence as a subset of it:
> **Pseudonymization** is a [data management](https://en.wikipedia.org/wiki/Data_management) and [de-identification](https://en.wikipedia.org/wiki/De-identification) procedure by which personally identifiable information fields within a data record are replaced by one or more artificial identifiers, or [pseudonyms](https://en.wikipedia.org/wiki/Pseudonym).<sup>[[1]](https://en.wikipedia.org/wiki/Pseudonymization#cite_note-1)</sup> A single pseudonym for each replaced field or collection of replaced fields makes the data record less identifiable while remaining suitable for [data analysis](https://en.wikipedia.org/wiki/Data_analysis) and [data processing](https://en.wikipedia.org/wiki/Data_processing).

 Perhaps we should use "_[de-identification](https://en.wikipedia.org/wiki/De-identification)_" in the broad sense, as defined by Wikipedia:
> **De-identification** is the process used to prevent someone's [personal identity](https://en.wikipedia.org/wiki/Personal_identity) from being revealed. For example, data produced during human subject research might be de-identified to preserve the privacy of research participants. Biological data may be de-identified in order to comply with [HIPAA](https://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act) regulations that define and stipulate patient privacy laws. <sup>[[1]](https://en.wikipedia.org/wiki/De-identification#cite_note-1)</sup>

**Comment by CPernet** [comment]
sure we can use that definition, I would still add that it's a concept from the US Health Insurance Portability and Accountability Act (HIPPA) **which does not involve irreversibility as anonymization does**

**Comment by CPernet** [comment]
don't have the ISO thing either

**Comment by DimitriPapadopoulos** [comment]
I'll add the glossary.

**Comment by DimitriPapadopoulos** [comment]
@CPernet Can you have a look at the updated merge request? I have added the glossary. Fell free to modify.

**Comment by DimitriPapadopoulos** [comment]
Here are the ISO documents:
* [ISO/IEC 29100:2011 _Information technology — Security techniques — Privacy framework_](https://www.iso.org/obp/ui/#iso:std:iso-iec:29100) is fully available online.
* [ISO 25237:2017 _Health informatics — Pseudonymization_](https://www.iso.org/obp/ui/#iso:std:iso:25237) is not fully available, but we do have access to the first pages, including "_3 Terms and Definitions_" which actually refer to the above ISO/IEC 29100:2011.

**Review by CPernet — CHANGES_REQUESTED** [review]
proposed to reverse for credits - the EU workshop discussed anonymization

**Comment by CPernet** [comment]
where is the glossary? couldn't not see it -- we need to define up front what we mean in the doc by de-identification and refer to the glossary

**Pull request merged**
